sudo: required
services:
  - docker

before_install:
  - docker build -t endy/docker-react -f Dockerfile.dev .

script:
  - docker run endy/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-788395112600'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
    #  DockerReact-env.fiiudnx39x.us-east-2.elasticbeanstalk.com
